### ISSUE TITLE
Differentiating attachments

### ISSUE THREAD

**Issue by richardlm** [melat0nin/zotero-roam-export#12]
I've created a new issue even though this is really a comment on #11 - I added this comment there but I'm not sure it is visible as the isue is closed.

Firstly, I really like the way that zotero-roam-export enhances the workflow between Zotero and Roam without the need to use any add-ons - it is immensely useful!

My comment is on the 'Zotero links'. The three types of link work as expected for me:

- Local library: open item record in local Zotero at the item's 'Info' tab
- Web library: open item record in web Zotero at the item's 'Info' tab
- "file name of PDF attachment.pdf": opens the PDF file in the default PDF reader

However, in my case, I often have the same PDF stored in two places:

- Zotero-controlled storage (which in my case is webdav, but could be Zotero storage) - an attachment that Zotero calls "Stored copy of file" and is the primary copy.
- Local storage, as a backup / failsafe if no internet - what Zotero calls "Link to file".

zotero-roam-export provides links to both, which is good and expected behaviour, but they look identical so I don't know which is the main (Zotero-controlled) copy.

Is it possible to differentiate these in the metadata presentation? If not, I could go through renaming one set but I would rather not.

Thanks again for this very helpful tool.

**Comment by melat0nin** [comment]
Okay I see your predicament (I use linked files, but they are stored in a OneDrive folder, so I have them always offline by default, as well as synced). I'll check whether the sources of the files can be differentiated, and add some kind of label to make it obvious.

**Comment by melat0nin** [comment]
Please give this version a try: [zotero-roam-export.zip](https://github.com/melat0nin/zotero-roam-export/files/4845494/zotero-roam-export.zip). You need to change the file's extension to `zip` before installing (Github doesn't allow uploading .xpi files in this context).

It labels linked files with the 🔗 emoji, like this:

![image](https://user-images.githubusercontent.com/912688/86006119-6e887800-ba0d-11ea-851e-ae8a95c3f37f.png)

**Comment by richardlm** [comment]
Yes, that is a neat solution - excellent! The icon is clear and does away with the need for any words, which are used inconsistently for attachments.

I'll add here an additional query but happy to turn into a new issue, or drop it... With a number of my Zotero items I have EPub attachments rather than PDF. I don't know how prevalent that is amongst Zotero users but it would be very helpful to be made aware of these attachments in the export, even if they cannot be opened by a default EPub reader. The link "zotero://select/library/items/<item-id>" (and web equivalent) would place the user at the right place, from where a click would open the item. What do you think?

Thanks again.

**Comment by melat0nin** [comment]
> 
> 
> Yes, that is a neat solution - excellent! The icon is clear and does away with the need for any words, which are used inconsistently for attachments.
> 
> I'll add here an additional query but happy to turn into a new issue, or drop it... With a number of my Zotero items I have EPub attachments rather than PDF. I don't know how prevalent that is amongst Zotero users but it would be very helpful to be made aware of these attachments in the export, even if they cannot be opened by a default EPub reader. The link "zotero://select/library/items/" (and web equivalent) would place the user at the right place, from where a click would open the item. What do you think?
> 
> Thanks again.

Glad it works.

Regarding epubs, I'm inclined to agree. The limitation to PDFs is a bit inflexible, even if it does cover most workflows. This should be relatively easy to implement, bear with me.

**Comment by richardlm** [comment]
Doh! I didn't mean to close the issue...

**Comment by melat0nin** [comment]
Implemented here https://github.com/melat0nin/zotero-roam-export/releases/tag/v1.9

**Comment by richardlm** [comment]
The way the epub links have been implemented (zotero://open-pdf/library/items/<itemid>), Zotero is opened but the focus does not go to the attachment, nor even to the item record.

Should these be of the form zotero://select/library/items/<itemid>?

**Comment by melat0nin** [comment]
🤦‍♂️ you're absolutely right, will fix asap. Copied the pdf code and missed this part.

**Comment by melat0nin** [comment]
I've fixed this in an updated version of 1.9: https://github.com/melat0nin/zotero-roam-export/releases/tag/v1.9

I've tested but let me know how you get on. AFAIK Zotero only automatically opens pdfs, so for those it uses the `open-pdf` handler, and for all other filetypes the `select` handler.

**Comment by richardlm** [comment]
Yes, that opens PDFs and goes to the epub attachment / link field as expected.
Many thanks.
