### ISSUE TITLE
Exporting in markdown as an option

### ISSUE THREAD

**Issue by argenos** [melat0nin/zotero-roam-export#14]
Would it be possible to add support for markdown? Although that might not be relevant for Roam, this tool is great and its functionality is a lot more universal!  Exports to markdown would help share annotations to non-roam users (via email!) and e.g. for people using Obsidian. This might be out of scope, but I thought I'd ask!

**Comment by melat0nin** [comment]
Thanks for the suggestion. I think you're describing a different (albeit useful) tool, however, which would require quite a lot of refactoring. There are probably other tools better equipped to do this -- various Zotero export translators exist to output various formats so they would be a good place to start. That said, if there was demand in the future this might serve as a basis for a separate markdown exporter.

There's also the possibility to convert from JSON to markdown -- something like this might do the trick https://github.com/IonicaBizau/json2md (untested)

**Comment by argenos** [comment]
I've used Zotfile for a while to extract annotations, but I haven't seen yet any other export plugins that combine both the metadata and my highlights and comments. But I understand that this might be not straightforward over here. Thanks for the suggestion! I'll give the repo above a try!

**Comment by melat0nin** [comment]
It's certainly a cool and useful idea, if I get some time I'll see how much work would be required to convert the output. I'd need to think about whether it merits a separate project though, given that it would no longer be Roam-specific, plus I'm sure it would be more complex than it might appear at first (these things always are).

**Comment by argenos** [comment]
Do you have any pointers on how to build the `xpi` from source files? I'm playing around with this locally, but have no idea how to test this. Thanks!

**Comment by melat0nin** [comment]
> Do you have any pointers on how to build the `xpi` from source files? I'm playing around with this locally, but have no idea how to test this. Thanks!

Just download the whole ~thing~ repo and zip it, then change the extension to .xpi (after making your changes, obvs). Testing within Zotero is a bit more involved; you have to close it first, then delete extensions.json from your Zotero profile folder, then replace the existing xpi in the extensions folder of your Zotero profile (make sure you use the identical file name). Alternatively, just remove the add-on, restart, add it, restart, then test (but this gets tedious pretty quickly!).

**Comment by linxule** [comment]
I made [this](https://github.com/linxule/themes/blob/master/Zotero/Roam-QuickCopy2MD.js) simple attempt to have Zotero write some info in MD as a QuickCopy option. Open to any suggestions and advice.

**Comment by argenos** [comment]
It took me a little while, but I ended up writing a plugin as well: https://github.com/argenos/zotero-mdnotes 

@linxule I also went through the translator -> plugin path as mentioned in #17 since I couldn't access a few things (collections and related items I believe). I like the quick copy translator though! Any way that we can use preferences to avoid roam-specific formatting?

**Comment by argenos** [comment]
@melat0nin thanks for the pointers, they helped a lot! I used your plugin as a starting point, so I added a little acknowledgement at the bottom of my README. I hope that's alright!

**Comment by melat0nin** [comment]
@argenos that's extremely cool, nice work! It's great you've worked out the preferences interface, that was my next challenge... I'll be borrowing some of your code back 😁

**Comment by argenos** [comment]
It's the least I can do! 😁

**Comment by linxule** [comment]
> It took me a little while, but I ended up writing a plugin as well: https://github.com/argenos/zotero-mdnotes 
> 
> @linxule I also went through the translator -> plugin path as mentioned in #17 since I couldn't access a few things (collections and related items I believe). I like the quick copy translator though! Any way that we can use preferences to avoid roam-specific formatting? 

Your plug-in looks amazing and I'm excited to try it soon! Using preferences to choose alternative formats makes sense and I am willing to give it a try. Would you be able to point me to some tools/softwares that might help facilitate this? Many thanks in advance!

**Comment by argenos** [comment]
@linxule I don't know if there's a better way to do it, but I tried to do that here: https://github.com/argenos/zotero-mdnotes/blob/master/content/mdnotes.js#L240
