### ISSUE TITLE
Export Abstract?

### ISSUE THREAD

**Issue by dropshot94** [melat0nin/zotero-roam-export#15]
Thank you for taking on this project. I'm new to Roam but a long-time Zotero user. I usually keep my basic notes about a document in the abstract field. Would it be possible to export that?

**Comment by melat0nin** [comment]
Yes this should be simple enough, I'll add it shortly 👍

**Comment by melat0nin** [comment]
Here you go: https://github.com/melat0nin/zotero-roam-export/releases/tag/v1.10

**Comment by dropshot94** [comment]
Looks good, thank you!
