### ISSUE TITLE
Add other creator types?

### ISSUE THREAD

**Issue by richardlm** [melat0nin/zotero-roam-export#16]
Hi

I don't know how far you want - or are able - to take this, but I have just exported an audio recording from Zotero and the metadata in Roam is `Author(s): false` .  The item does have a `Performer` associated with it.

- Is it possible to capture this?
- If not, is it possible to at least show 'Creator' as a generic field indicating someone who has had some responsibility for the item's creation?

Author / editor will cover the majority of items but it it would good to capture the other creator types. 

Thanks.

**Comment by melat0nin** [comment]
I agree this would add a lot of flexibility. I think it should be possible to cycle through Zotero's creator types and output them, whatever they are for a given item. I'll take a look!

**Comment by melat0nin** [comment]
**[v1.11](https://github.com/melat0nin/zotero-roam-export/releases/tag/v1.11)** implements this, let me know how you get on. You should be able to update the addon from within Zotero too -- let me know if that works.

(Edit: you can only update from within Zotero if you're already running v1.10.1)

**Comment by dropshot94** [comment]
When I opened Zotero, the addon did not update or offer to update. I
changed the setting for autoupdate for the addon from default to on, and it
will didn't work.

Sorry. :(

**Comment by melat0nin** [comment]
What version are you running currently?

19 Jul 2020, 14:39 by notifications@github.com:

>
>
>
> When I opened Zotero, the addon did not update or offer to update. I
>  changed the setting for autoupdate for the addon from default to on, and it
>  will didn't work.
>  
>  Sorry. :(
>

**Comment by dropshot94** [comment]
I'm on Zotero 5.0.88 and zotero-roam-export 1.10.1

**Comment by melat0nin** [comment]
> 
> I'm on Zotero 5.0.88 and zotero-roam-export 1.10.1

Try manually checking for an update on the addon's entry in the interface (cog icon), failing which just download v1.11 manually. But updating should work 🤔

**Comment by dropshot94** [comment]
The manual check worked.

**Comment by richardlm** [comment]
Hi
I have successfully imported items:
- Creator field set to 'Performer'
- Creator field set to 'Editor'
- Creators set as an author and two contributors
- Web page with no author

The add-on had also updated to v1.11 from 1.10.1.

Many thanks for these improvements!

**Comment by melat0nin** [comment]
> 
> 
> Hi
> I have successfully imported items:
> 
>     * Creator field set to 'Performer'
> 
>     * Creator field set to 'Editor'
> 
>     * Creators set as an author and two contributors
> 
>     * Web page with no author
> 
> 
> The add-on had also updated to v1.11 from 1.10.1.
> 
> Many thanks for these improvements!

Glad it's working 🎉
