### ISSUE TITLE
Quick Copy via Translator?

### ISSUE THREAD

**Issue by linxule** [melat0nin/zotero-roam-export#17]
Hi Laurence, 

Thank you so much for making this Add-on!

Would you be able to provide some guidance as to how I can use your codes for a "translator" in Zotero? So it would be possible to use QuickCopy in Zotero to copy the output (in the format that is shown in Roam) in .txt or .md and paste into Roam. This would be great for quickly adding one or two articles to Roam. 

I have tried to incorporate your codes into a couple of Zotero translators, but so far I have not made it work. Any tips will be appreciated!

**Comment by melat0nin** [comment]
Glad it's useful!

This addon actually came out of a translator, but translators only have limited access to the Zotero database so I had to refactor into a full addon. You can find the old translator code here: https://github.com/melat0nin/translators/blob/master/Roam%20JSON.js

Are you having trouble exporting just one or two items with the full addon? I guess that isn't Quick Copy, to be fair. It would probably make sense to adapt another translator to output MD for pasting...

**Comment by linxule** [comment]
Thank you for the prompt reply! Sorry that my original post was a bit confusing. The full addon works great for me. I was mainly wondering if it could be modified and used as QuickCopy and, like you said, output MD for pasting. 

Relatedly, I was wondering if the JSON output can be fed directly to Alfred or ZotHero on Alfred so that JSON output can be parsed and formatted in MD. (Just a thought as I don't have enough knowledge on the topic.)

And thank you for the old translator code. I will give it a try!

**Comment by melat0nin** [comment]
I don't use Alfred or ZotHero so I can't comment on that. In terms of outputting to MD, this was requested [elsewhere ](https://github.com/melat0nin/zotero-roam-export/issues/14 )and I agree it would be useful, but I think it's a different project.

I guess it should be possible to use the translator framework to output to the clipboard rather than a file, but that will only be useful if what's copied is in MD/some other unformalised format, which brings us back to the point above. Quickcopying JSON wouldn't work because you'd be pasting that raw into Roam, which isn't much use.

I think for that reason I'll close this issue, since I think it's really a separate project.

**Comment by linxule** [comment]
Thank you, Laurence. [Here](https://github.com/linxule/themes/blob/master/Zotero/Roam-QuickCopy2MD.js) is my attempt to just have Zotero write a couple of key info. Would love to learn more as to add additional information in the output, especially the "collections as topics".

**Comment by melat0nin** [comment]
> "collections as topics"

I'm afraid that's precisely the thing that a translator can't access, and the main reason I moved to a full addon. It seems bizarre, but the translator code is sandboxed and can't access other parts of the Zotero database in the way an addon can 😢

**Comment by linxule** [comment]
Ah, it makes more sense for you switching to a full add on. That's too bad. Btw, is there any way to get the BBT citekey via translator? I thought about calling the BBT QUickCopy translator but wasn't sure if it's worth even pursuing it.

**Comment by linxule** [comment]
Thanks for the explanation! Keep up the good work!
