### ISSUE TITLE
Two indented items in a row stop export

### ISSUE THREAD

**Issue by jerudnik** [melat0nin/zotero-roam-export#19]
Started using optional feature 3 with highlighted text that I've formatted as blockquotes. Not sure if this is due to errors in the way that I'm using it, but if there's two blockquotes without any break between them, the exporter doesn't seem to work. This could be a feature, to prevent lots of indented comments (in my case, text), but sometimes it can be useful to have multiple bits of text underneath a comment. I've posted a screenshot of what the double blockquotes bits of text look like for me.

![image](https://user-images.githubusercontent.com/43145353/88857328-14bdce00-d1c4-11ea-963b-66c63d342766.png)

**Comment by melat0nin** [comment]
Semantically this isn't really ideal; each blockquote should contain a single quote. I know it makes sense to the human reader but it breaks down the intended structure of the tags. I'd therefore recommend you split such blocks into two separate blockquotes (just put a carriage return after the first one, which will show as a break in the blue line on the left).

**Comment by jerudnik** [comment]
Ah - I didn't realize that a carriage return would allow for this. I think what you're discussing here is the result I've been going for, but I adjusted my annotation strategy around this.

When this happened, I had spent awhile figuring out why the file wouldn't export it, and wanted to put it on the record so others didn't run into a similar problem. Appreciate your response and will close this.

**Comment by melat0nin** [comment]
Let me know if it works once you do that 😃

**Comment by jerudnik** [comment]
Hey - so I tried a hard line break, and just ended up with a block quote nested under a bullet with no text, but the export worked!

![image](https://user-images.githubusercontent.com/43145353/89736647-e26c6600-da38-11ea-81d5-bfeefdb4ce89.png)

I supposed it's easy enough to fix this within roam, but might become more annoying with longer documents.
