### ISSUE TITLE
Feature request: Date added field

### ISSUE THREAD

**Issue by rushikb** [melat0nin/zotero-roam-export#2]
Hi Laurence, 

first of all, this is an absolutely brilliant plug in, and just works perfectly. I did have a quick request though, would it also be possible to add an attribute to pull in date added metadata? it would really help in tracking paper input

**Comment by melat0nin** [comment]
Would it be useful to tag the dates in the same format as Roam's, so the imports show up on the daily notes for the relevant day? Or would that confuse Roam and Zotero's metadata?

**Comment by rushikb** [comment]
I think having it in the Roam format would be best, just so it becomes a version of inboxing. Might mess with the logs of people who have a long older history with Zotero though.

**Comment by melat0nin** [comment]
This is done, although I'm wondering about what the variable name should be. Currently `Date` refers to item's publication date, which seems clear and obvious independent of the fact the page is imported. Do you think this new value should be stored in `Date added`? Within the Roam context this might be misleading -- implying that that's the date it was added to Roam, as opposed to Zotero.

See e.g.

![image](https://user-images.githubusercontent.com/912688/83348369-c3a86f80-a323-11ea-8cc8-3007beb545fc.png)

Maybe it doesn't matter that much in practice. Let me know what you think. Once this is set I'll push a new release.

Btw very early dates don't seem to matter -- Roam takes them in its stride, as far as I can tell.

**Comment by rushikb** [comment]
I think Date added makes sense, because the import will push everything under the same tag.

I imagine the easiest way out is to create a customizable config sheet, given the questions from people asking for citekey integration— but I imagine that could get very difficult very quickly. 

I'm very new to Javascript, so apologies for not being able to help on the code directly. But very happy to help with admin/ documentation if needed.

**Comment by melat0nin** [comment]
Okay I'll push on that basis -- I agree it's not that hard to understand.

Yes ultimately it would be good to have a GUI for selecting and/or adapting the fields that are shown and the variable names they have in Roam -- but that's for the longer term 😉
