### ISSUE TITLE
Nesting Metdata

### ISSUE THREAD

**Issue by FHeimburger** [melat0nin/zotero-roam-export#21]
Hi,
thanks for all the hard work - I love the extension which is proving endlessly useful.
One quick question: following on from Conor's Tweet here https://twitter.com/Conaw/status/1289654179900735488 I am trying to decide whether I should nest Metadata under a common block or not. Might be worth making that an option for the export?

**Comment by melat0nin** [comment]
See the discussion here #20

**Comment by FHeimburger** [comment]
Thanks, missed that one!

**Comment by melat0nin** [comment]
@FHeimburger what are your thoughts? I'm still not convinced of the value of the approach, but I might have missed something. Unless there's a solid reason to implement this I'll close the issue.
