### ISSUE TITLE
can't get an export

### ISSUE THREAD

**Issue by ccpalmer** [melat0nin/zotero-roam-export#22]
This is precisely the tool I need, but I can't get it to work (Mac OSX 10.15.6).  

I get the `.xpi` installed and have restarted Zotero several times.  I right click on a PDF with a couple of highlights (saved, no longer open), and I get the menu.  I select "Export item(s) to Roam" and nothing happens.

What dumb mistake have I made?

**Comment by melat0nin** [comment]
You need to right-click and export the item, not the PDF (the item is the parent of the PDF in your zotero window):

![image](https://user-images.githubusercontent.com/912688/90644533-bd43d880-e22c-11ea-8606-20b097520f7d.png)

**Comment by ccpalmer** [comment]
Duh ... thanks!
