### ISSUE TITLE
No annotations

### ISSUE THREAD

**Issue by ccpalmer** [melat0nin/zotero-roam-export#23]
I created an "item" and then tried attaching the pdf as "stored copy" and "link to" the pdf, then I annotated it with three highlights, saved, and closed Preview.  Then a right click on the item did bring up your dialog, I selected export item(s) to roam, and I still get the same 482 byte JSON file that has no annotations:

```
[{"title":"NIST 800-154-draft","children":[{"string":"Metadata::","heading":2,"children":[{"string":"Type:: [[undefined]]"},
{"string":"Topics:: "},{"string":"Date added:: [[August 19th, 2020]]"},{"string":"Zotero links:: [Local library]
(zotero://select/library/items/2T4EWVPM), [Web library](https://www.zotero.org/users/6573053/items/2T4EWVPM), 
[sp800_154_draft.pdf 🔗](zotero://open-pdf/library/items/6YUZTPB8)"},{"string":"Tags:: #[[ZoteroImport]]"}]}],"edit-
time":1597871902}]
```

I'm sorry to be such a novice here, but can you tell me what I'm doing wrong?

**Comment by melat0nin** [comment]
Did you extract the annotations into a note (Zotfile does this, or you could create the notes manually as child items of the main item)? The exported doesn't extract annotations from the PDF itself; it only exports what's stored in Zotero :)

**Comment by ccpalmer** [comment]
OH … My highlights were directly in the PDF … I’ll go look for Zotfile.

I’ll close

On Aug 19, 2020, at 1:50 PM, melat0nin <notifications@github.com<mailto:notifications@github.com>> wrote:



Did you extract the annotations into a note (Zotfile does this, or you could create the notes manually as child items of the main item)? The exported doesn't extract annotations from the PDF itself; it only exports what's stored in Zotero :)
