### ISSUE TITLE
no file picker dialog

### ISSUE THREAD

**Issue by rhaynes74** [melat0nin/zotero-roam-export#24]
Hi folks, I am using the latest zotero 5.0.89 on a mac book pro.   I installed the roam-export, no problems, restarted zotero.  Selected all articles in my database (about 2200), right-clicked and selected export to roam, but no file picker appeared.  Zotero didn't seem to freeze or anything, no sign that anything happened.

**Comment by cohubicol** [comment]
That's a lot of articles, I'm not surprised something wasn't right 😅

Try opening the debug output (`Help` > `Debug Output Logging` > `View output`) then do the export again, and paste the output here!

**Comment by melat0nin** [comment]
That's a lot of articles, I'm not surprised something wasn't right 😅

Try opening the debug output (Help > Debug Output Logging > View output) then do the export again, and paste the output here -- there should be an error somewhere in there.

**Comment by rhaynes74** [comment]
[JavaScript Error: "XML Parsing Error: no root element found
Location: https://rhaynes74%40gmail%2Ecom:****@webdav.4shared.com/zotero/
Line Number 1, Column 1:" {file: "https://rhaynes74%40gmail%2Ecom:****@webdav.4shared.com/zotero/" line: 1}]

version => 5.0.89, platform => MacIntel, oscpu => Intel Mac OS X 10.15, locale => en-CA, appName => Zotero, appVersion => 5.0.89, extensions => Zotero Scholar Citations (1.9.3, extension), ZotFile (5.0.16, extension), Better BibTex for Zotero (5.2.47, extension), Zotero LibreOffice Integration (5.0.23.SA.5.0.89, extension), Zotero Word for Mac Integration (5.0.27.SA.5.0.89, extension), Zotero Roam Export (1.11, extension)

(3)(+0000000): Viewing item in pane 0

(3)(+0000001): Refreshing item box

(3)(+0007998): Error: getAttachments() cannot be called on attachment items Zotero.Item.prototype.getAttachments@chrome://zotero/content/xpcom/data/item.js:3228:11 getItemMetadata@chrome://zoteroroamexport/content/roamexport.js:214:13 gatherItemData@chrome://zoteroroamexport/content/roamexport.js:321:24 getAllItemsData@chrome://zoteroroamexport/content/roamexport.js:336:28 exportItems@chrome://zoteroroamexport/content/roamexport.js:346:28

(5)(+0089737): POST /connector/ping HTTP/1.1 Host: 127.0.0.1:23119 Connection: keep-alive Content-Length: 73 X-Zotero-Version: 5.0.69 X-Zotero-Connector-API-Version: 2 User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36 Content-Type: application/json Accept: */* Origin: chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc Sec-Fetch-Site: none Sec-Fetch-Mode: cors Sec-Fetch-Dest: empty Accept-Encoding: gzip, deflate, br Accept-Language: en-US,en;q=0.9

(5)(+0000009): HTTP/1.0 200 OK X-Zotero-Version: 5.0.89 X-Zotero-Connector-API-Version: 2 Content-Type: application/json {"prefs":{"automaticSnapshots":true}}

**Comment by melat0nin** [comment]
`(3)(+0007998): Error: getAttachments() cannot be called on attachment items Zotero.Item.prototype.getAttachments@chrome://zotero/content/xpcom/data/item.js:3228:11 getItemMetadata@chrome://zoteroroamexport/content/roamexport.js:214:13 gatherItemData@chrome://zoteroroamexport/content/roamexport.js:321:24 getAllItemsData@chrome://zoteroroamexport/content/roamexport.js:336:28 exportItems@chrome://zoteroroamexport/content/roamexport.js:346:28`

From this it looks like somewhere within your selection you've included attachments as well as parent items. The exporter only exports parent items (but it includes attachment metadata). Try checking to make sure you're only selecting parent items before exporting.

**Comment by rhaynes74** [comment]
hmmm... it doesn't look like I have included attachments in the selection.  I have the article list collapsed, cmd-a selects them all, hitting the little triangle shows that the pdf/attachment is not selected.  Is there a setting somewhere that would override this?

**Comment by melat0nin** [comment]
Are there perhaps items that are just files (i.e. have no parent items) at the bottom of your list? Sometimes that happens when you import a file but don't create a parent item for it.

Like the Unger PDF below:

<img src="https://user-images.githubusercontent.com/912688/91463506-c0be0c00-e88b-11ea-819a-4a02f8206b90.png" width="300"/>

**Comment by rhaynes74** [comment]
Hi - that is absolutely possible, many thanks, I will check.

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by rhaynes74** [comment]
Indeed - there was a couple of pdfs at the bottom of the list.  So I now have the .json file, but roam/browser becomes unresponsive upon import.  It correctly recognizes the number of files but when I confirm the import is stalls.  The browser gives unresponsive warnings.

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by melat0nin** [comment]
If the JSON successfully exports then that implies the export is just too large -- I'd recommend splitting it into chunks, since 2,000 is a huge number for Roam to process in a single import.

**Comment by melat0nin** [comment]
Let me know if chunking your exports worked. The problem was most probably that the javascript engine coupled with your hardware couldn't handle an export of that size, which isn't unreasonable, I think.

**Comment by rhaynes74** [comment]
Yes - chunking seemed to work fine!
