### ISSUE TITLE
Export underlining issue

### ISSUE THREAD

**Issue by cobblepot1** [melat0nin/zotero-roam-export#25]
First, thank you so much for this extension and implementing the citekey as title option!

When I export/import my Zotfile extracted annotations into Roam, my comments on the pdf (not highlights, but comments) are not formatted correctly. Zotfile is set at this default:

`extensions.zotfile.pdfExtraction.formatAnnotationUnderline` = `<p>"<u>%(content)</u>" (%(cite))</p>`

This produces the following text in Roam:
`__Here, he implies that existence beliefs are central to emotions. ([note on p.11](zotero://open-pdf/library/items/M8Z6HYN2?page=11))__`

Because the double underscore follows the link, it does not properly italicize the text. It would be great if you can fix this to retain the italics formatting.

Also, I would like to automatically indent my comments on the extracted highlights so it looks like this:

- "Highlighted text extracted from pdf"
     - _The comment I added to this highlight as a pdf annotation, in italics_

I see the formatting tag option but I'm not sure how to utilize it. Can you explain? Do I just put `<u>` in that field?

**Comment by melat0nin** [comment]
The first problem is with Roam, unfortunately -- when italicised text includes a link the markdown parser seems to break and fail to italicise everything between the two sets of `--`. I imagine this will be fixed at some point but it's not part of the exporter. Having said that, looking at your Zotfile setting it doesn't look like there's any reason for the extracted text to be italicised -- the exporter doesn't by default convert either `<p>` or `<u>` tags into italics (see lines [258](https://github.com/melat0nin/zotero-roam-export/blob/8cfbbd7cd635ae2f51b5f56888806ca5240c2209/chrome/content/roamexport.js#L258)-259 of [roamexport.js](https://github.com/melat0nin/zotero-roam-export/blob/master/chrome/content/roamexport.js)):

`mapObj = {"<p>":"","</p>":"","<strong>":"**","</strong>":"**","<b>":"**","</b>":"**","<u>":"### ","</u>":"","<em>":"__","</em>":"__",
                "<blockquote>":"> ","</blockquote>":"","<br><br>":"\n\n"},`

Have you changed something manually?

For your second issue, this is taken care of by the `extensions.roamexport.indent_tag_as_child` exporter option. You can set whatever tag you like and it'll always be indented under the preceding block. I have adapted my Zotfile settings to extract all my highlight-attached-notes as `<blockquote>`s, which I then target using the above preference to indent them, like this:

<img src="https://user-images.githubusercontent.com/912688/85718009-fdcc1d80-b6e5-11ea-9647-a26921e39589.png"/>

There's more info about these options in the README under [Optional features](https://github.com/melat0nin/zotero-roam-export#optional-features). I hope to add them to a GUI sometime soon but have been very busy with other things the past few months.

**Comment by cobblepot1** [comment]
Thanks for the response. I actually want my notes to look just like yours - the quote normal and the comment in italics. Can you share your Zotfile and any other relevant settings I need to do that?

**Comment by melat0nin** [comment]
Here are my settings:

- `extensions.zotfile.pdfExtraction.formatAnnotationHighlight` -> `<p>%(content) (%(cite))</p>`
- `extensions.zotfile.pdfExtraction.formatAnnotationNote` -> `<blockquote><i>%(content)</i></blockquote>`
- `extensions.zotfile.pdfExtraction.formatAnnotationUnderline` -> `<p><u>%(content)</u></p>`
- `extensions.roamexport.convert_underline_to_heading` -> `true`
- `extensions.roamexport.indent_tag_as_child` -> `<blockquote>`

**Comment by cobblepot1** [comment]
Thanks!
