### ISSUE TITLE
Selective export - feature request

### ISSUE THREAD

**Issue by cobblepot1** [melat0nin/zotero-roam-export#26]
Hi, this add-on has transformed my workflow for the better - many thanks! But there is one issue. For my workflow, I have the source in Zotero, export it to Roam, take notes in roam as I read, and highlight/comment on the pdf while taking notes in Roam. The problem is that when I am done, I use Zotfile to extract annotations, which puts them in a Zotero note, and then I need to get them into Roam. If I use zotero-roam-export to do it, I have to export everything again, which duplicates all of the metadata (title, author, etc.) in the Roam page. I would like a way to import the extracted annotation without duplicating this information. Thanks.

**Comment by melat0nin** [comment]
That isn't possible I'm afraid, at least not without serious work to keep track of what's already in the Roam database (could be done e.g. by keeping track of block IDs, but that would risk collisions and would be a huge expansion of the simplicity of this exporter for a relatively niche function).

**Comment by cobblepot1** [comment]
Many thanks for replying. My last sentence is misleading - I was really thinking about selective *export* as said in the title, not selective import. It is possible to have JSON export not just of an item and all child items, but also JSON export of a single child item (such as a Zotero 'Extracted Annotations' note) with the same Roam page name? Then the Roam import would automatically merge the child item info with the correct page.

**Comment by melat0nin** [comment]
Ah okay -- exporting only a single note is a less precipitous challenge! However, in terms of merging all that would happen is the imported text would be added to the bottom of the page -- Roam (AFAIK) doesn't do any clever merging, e.g. such that child blocks of parents with the same text get merged under the one parent.

Given the merging is 'dumb' I'm not clear there's much to be gained from this over simply doing it manually, since you'd need to rationalise your newly-'merged' note anyway.

**Comment by cobblepot1** [comment]
What do you mean exactly by "doing it manually"? Do you mean highlighting all of the text in the Zotero note and copy/pasting it into Roam? The disadvantage of that is that I lose formatting and markdown links from the quotes to the correct location in my pdf. I know that you don't use those (based on your settings), but I do.

Or did you mean something else?
