### ISSUE TITLE
Export does not thing after a while, has to restart Zotero.

### ISSUE THREAD

**Issue by lkhphuc** [melat0nin/zotero-roam-export#27]
Just a minor bug, when after a while the export button does nothing.
I have to restart Zotero completely to get this functionality back.

**Comment by melat0nin** [comment]
If you can recreate this and show me the debug output I can try to diagnose the problem!

**Comment by lkhphuc** [comment]
```
(3)(+0001773): NS_ERROR_FAILURE Exception: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIFilePicker.init] init@chrome://zotero/content/modules/filePicker.js:60:258 writeExport@chrome://zoteroroamexport/content/roamexport.js:375:9
```
this is what show up in the debug log after I clicked export to Roam.

**Comment by melat0nin** [comment]
Interesting, I think it has something to do with asynchronous processing, but the problem seems to lie with the filepicker library. Did you have another filepicker open at the time? In any event, I wonder if this is an edge case that will be difficult to replicate.

**Comment by lkhphuc** [comment]
Sorry I have no idea what is a filepicker and a quick search doesn't help.
But yeah this is probably just a weird edge case not with an easy work around so not worth spending time on it.

**Comment by melat0nin** [comment]
It's the thing that pops up where you specify the name of and the location for the export -- it's part of Zotero's internals and not this exporter.

I'll close this issue for now 👍
