### ISSUE TITLE
Import error: b.text is not a function. (In 'b.text()', 'b.text' is undefined)

### ISSUE THREAD

**Issue by danieltomasz** [melat0nin/zotero-roam-export#3]
I cannot import any item from zotero, I always get this error

**Comment by melat0nin** [comment]
Where do you see the error? In Zotero or in your browser?

`b.text()` isn't a call used in the addon; I think your error might be elsewhere.

**Comment by melat0nin** [comment]
This seems to be an issue with Safari; Roam suggest using Chrome or Firefox: https://www.reddit.com/r/RoamResearch/comments/gcxl5b/hi_all_i_am_getting_the_following_error_when_i/

**Comment by danieltomasz** [comment]
Thanks for pointing for this resource!
