### ISSUE TITLE
export to MD files

### ISSUE THREAD

**Issue by trungng2006** [melat0nin/zotero-roam-export#31]
Would it be possible if you could adapt this plugin to export MD files? (for program like Obsidian)
I would suggest that there are 2 types of file:
1. Notes and highlights (each note and highlights will have their own unique ID)  
2. the integration file. This file will have the article metadata and it also embed all the notes and highlights  (![[highlight unique ID]])
So the integration file would look like this:
https://ibb.co/hmMT14t

**Comment by melat0nin** [comment]
See the discussion in #14 for why I decided not to proceed with this.

**Comment by trungng2006** [comment]
Thank you for your response!
