### ISSUE TITLE
Unable to export items more than 7 at the same time

### ISSUE THREAD

**Issue by imane0897** [melat0nin/zotero-roam-export#34]
Hi, there! I have successfully installed this add-on and it's awesome. But I've got trouble in exporting multiple items. It just appears nothing when I try to export a collection that contains more than 500 items. And when selecting manually, it is not possible to export more than 7 items at the same time.

I have tried restarting and reinstall but it still doesn't work. I'm using Zotero 5.0.91 on macOS Catalina 10.15.5 with zotero-roam-export-1.11.

Thank you for your time.

**Comment by melat0nin** [comment]
Please try again and paste the debugging output (instructions here: https://www.zotero.org/support/debug_output)

In principle the addon exports an unlimited number of items, so I think the problem lies in what you're trying to export, rather than the number.

**Comment by imane0897** [comment]
Yes, you are right. It's because one file is a single PDF file.
The debugging output is as follows.

```
(4)(+0008574): SELECT synced FROM fulltextItems WHERE itemID=? [1198]

(4)(+0000003): SELECT indexedPages, totalPages AS total FROM fulltextItems WHERE itemID=? [1198]

(3)(+0000012): MIME type application/pdf cannot be handled internally

(3)(+0002260): Error: getAttachments() cannot be called on attachment items Zotero.Item.prototype.getAttachments@chrome://zotero/content/xpcom/data/item.js:3228:11 getItemMetadata@chrome://zoteroroamexport/content/roamexport.js:214:13 gatherItemData@chrome://zoteroroamexport/content/roamexport.js:321:24 getAllItemsData@chrome://zoteroroamexport/content/roamexport.js:336:28 exportItems@chrome://zoteroroamexport/content/roamexport.js:346:28
```

Thank you for your help. I'll close this issue.
