### ISSUE TITLE
Automatic import to Roam

### ISSUE THREAD

**Issue by bermudezrey** [melat0nin/zotero-roam-export#35]
Downloading the JSON files and inputting them into Roam is a repetitive task, and it seems like it could be automated... Being able to do this without manual labor for every exported file would be a fantastic time saver. Is there a way the extension could achieve that? (Apologies if this isn't relevant, I'm not sure whether this is achievable from within a Zotero extension.)

**Comment by melat0nin** [comment]
Agreed, but this won't/can't happen until the API is released. Will close for now.
