### ISSUE TITLE
want to export the references

### ISSUE THREAD

**Issue by flyq** [melat0nin/zotero-roam-export#38]
when exporting the paper, there are not references of the paper in the the metadate, and so it can't be bilinked in roam. but it is important for roam. 

references is mapped by the title of paper, so they can be linked in roam

**Comment by cobblepot1** [comment]
Zotero doesn't store paper references in fields that can be easily exported. This add-on is for exporting data that's already in Zotero. The functionality you want isn't appropriate for this add-on.

You could potentially highlight the references list in the paper's pdf and use the add-on Zotfile to extract those references to a Zotero note. Zotero-roam-export will then include that note text in its export. Finally, if you have Roam pages for those papers, they will show up in "Unlinked references" on the papers' Roam pages, and you can link them there.

**Comment by flyq** [comment]
Thanks, highlight is a good solution, and scholarcy(a chrome extension) is also useful.
