### ISSUE TITLE
Feature Request: Add Better BibTex Citation Key

### ISSUE THREAD

**Issue by wshuyi** [melat0nin/zotero-roam-export#4]
Thank you so much for this fantastic Zotero addon! It's quite mind-blowing.

Would you please also include the Better BibTex Citation Key in the metadata? In that way, the user don't need to go back to Zotero to copy it manually when they want to cite the item. 

Thanks a lot!

**Comment by melat0nin** [comment]
Great idea + should be very simple, I'll investigate 👍

**Comment by wshuyi** [comment]
Thanks! I am looking forward to that new feature. :)

**Comment by melat0nin** [comment]
Here's an initial pass:

![image](https://user-images.githubusercontent.com/912688/84494730-e9c5fc00-aca1-11ea-8dee-3e8e46d428cc.png)

Is that a suitable way of displaying the key and its value? Could make the key a link (but not sure if that's valuable).

**Comment by wshuyi** [comment]
Terrific! Exactly what I need. Thanks a lot! :)

**Comment by melat0nin** [comment]
Great, I'll package it and create a new release.

**Comment by melat0nin** [comment]
New release here: https://github.com/melat0nin/zotero-roam-export/releases/tag/v1.3
