### ISSUE TITLE
Editors not exported

### ISSUE THREAD

**Issue by richardlm** [melat0nin/zotero-roam-export#6]
Firstly, I'm really pleased you've developed this - an excellent contribution to the academic workflow.

I noticed an issue, however. The export appears to only catch authors, not editors. So the item I just exported from Zotero is an edited collection with 2 editors, but the JSON doesn't include them.

Is this something you'd consider fixing?

Thanks.

**Comment by melat0nin** [comment]
That's true. I left them out because I thought at first they wouldn't add much to my own workflow, but I can see in hindsight that that was a bit limiting. This will be very simple to add, give me a few days :)

**Comment by melat0nin** [comment]
Implemented here: https://github.com/melat0nin/zotero-roam-export/releases/tag/v1.4

**Comment by richardlm** [comment]
Excellent - many thanks. Richard


On Fri, Jun 12, 2020 at 5:11pm, melat0nin < notifications@github.com [notifications@github.com] > wrote:

Implemented here: https://github.com/melat0nin/zotero-roam-export/releases/tag/v1.4 [https://github.com/melat0nin/zotero-roam-export/releases/tag/v1.4]
